using Newtonsoft.Json;

namespace GlobalCollect.Schema
{
    public class PaymentReferences
    {
        /// <summary>
        /// Your order ID for this transaction that is also returned in our report files
        /// </summary>
        [JsonProperty("merchantOrderId")]
        public int MerchantOrderId { get; set; }

        /// <summary>
        /// Your unique reference of the transaction that is also returned in our report files. This is almost always used for your reconciliation of our report files.
        /// </summary>
        [JsonProperty("merchantReference")]
        public string MerchantReference { get; set; }

        /// <summary>
        /// Payment Reference generated by WebCollect
        /// </summary>
        [JsonProperty("paymentReference")]
        public string PaymentReference { get; set; }

        /// <summary>
        /// Provides an additional means of reconciliation for Gateway merchants
        /// </summary>
        [JsonProperty("providerId")]
        public string ProviderId { get; set; }

        /// <summary>
        /// Provides an additional means of reconciliation for Gateway merchants
        /// </summary>
        [JsonProperty("providerReference")]
        public string ProviderReference { get; set; }

        /// <summary>
        /// When you did not supply a merchantReference for your payment, you need to fill this field with the reference of the original payment when you want to refund it
        /// </summary>
        [JsonProperty("referenceOrigPayment")]
        public string ReferenceOrigPayment { get; set; }
    }
}