using Newtonsoft.Json;

namespace GlobalCollect.Schema
{
    public class PayoutReferences
    {
        /// <summary>
        /// Your invoice number (on printed invoice) that is also returned in our report files
        /// </summary>
        [JsonProperty("invoiceNumber")]
        public string InvoiceNumber { get; set; }

        /// <summary>
        /// Order Identifier generated by the merchant Note: This does not need to have a unique value for each transaction
        /// </summary>
        [JsonProperty("merchantOrderId")]
        public int MerchantOrderId { get; set; }

        /// <summary>
        /// Your unique reference of the transaction that is also returned in our report files. This is almost always used for your reconciliation of our report files. Required
        /// </summary>
        [JsonProperty("merchantReference")]
        public string MerchantReference { get; set; }
    }
}